name: Add whitelist user

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'TG User ID'
        required: true

jobs:

  update-config:
    name: Update Config
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VULTR_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.VULTR_SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Update config.py and Restart Service
      env:
        VULTR_SSH_HOST: ${{ secrets.VULTR_SSH_HOST }}
        USER_ID: ${{ github.event.inputs.id }}
      run: |  
        ssh root@$VULTR_SSH_HOST << EOF
          set -e
          cd ~/TranslatorBot
          
          python3 update-config.py "$USER_ID"
          
          sudo systemctl restart translatorbot.service
        EOF